NAME = replace
SOURCES = main.cpp

OBJECTS = $(SOURCES:%.cpp=%.o)

CFLAGS = -Wall -Wextra -Werror -g3 -std=c++98
RM = rm -f
CC = c++

%.o: %.cpp
	$(CC) $(CFLAGS) -c $< -o $@
 
all: $(NAME)
$(NAME): $(OBJECTS)
	$(CC) $(CFLAGS) -o $(NAME) $(OBJECTS)

e:
	$(RM) $(OBJECTS)

fe: e
	$(RM) $(NAME)

re: fe all

.PHONY: all e fe re
